/**
 * Icon registry.
 *
 * Every icon the app uses is imported once here and re-exported under a
 * semantic name. Two reasons: pages refer to "emergency" rather than a specific
 * glyph, and if an icon name ever changes upstream there is exactly one file to
 * edit instead of thirty.
 */

import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Ban,
  BarChart3,
  Building,
  Building2,
  Calculator,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Database,
  Download,
  Droplet,
  Droplets,
  FileText,
  Filter,
  FlaskConical,
  HeartHandshake,
  Info,
  Landmark,
  LayoutDashboard,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  Pencil,
  Phone,
  Plus,
  RefreshCw,
  Search,
  Send,
  ShieldCheck,
  Stethoscope,
  TrendingUp,
  UserRound,
  Users,
  X,
  XCircle,
} from "lucide-react";

/** Domain icons, keyed by the names used in navigation.js and page headers. */
export const ICONS = {
  dashboard: LayoutDashboard,
  donors: HeartHandshake,
  recipients: UserRound,
  doctors: Stethoscope,
  donations: Droplet,
  bloodUnits: Droplets,
  emergency: AlertTriangle,
  reservations: ClipboardCheck,
  organs: Activity,
  hospitals: Building2,
  bloodBanks: Building,
  organBanks: Landmark,
  camps: CalendarDays,
  reports: BarChart3,
  audit: FileText,
  users: ShieldCheck,
  clock: Clock,
  trends: TrendingUp,
  tests: FlaskConical,
  database: Database,
  records: ClipboardList,
};

/** Resolve a registry key to a component, falling back to a neutral glyph. */
export function iconFor(name) {
  return ICONS[name] || ClipboardList;
}

export {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Ban,
  BarChart3,
  Building,
  Building2,
  Calculator,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Database,
  Download,
  Droplet,
  Droplets,
  FileText,
  Filter,
  FlaskConical,
  HeartHandshake,
  Info,
  Landmark,
  LayoutDashboard,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  Pencil,
  Phone,
  Plus,
  RefreshCw,
  Search,
  Send,
  ShieldCheck,
  Stethoscope,
  TrendingUp,
  UserRound,
  Users,
  X,
  XCircle,
};
